* Jumping-off point

Consider the DA:O system.

It has a set of "Conditions" which boil down to [Target][Condition] -> [Action].

An example would be [Ally: Health < 25%] -> [Heal]

However, one thing to note is that DA:O has *no concept of positioning*. So
there's no condition corresponding to:

[Enemy: Adjacent] -> [Run Away]

Another thing to note is that there's *no composition* of the statements - you
can't make the statements:

[Ally: Health < 25%] AND [Enemy using ranged attack] -> [Deflect Missiles]
[Ally: Health < 25%] AND [Enemy using melee attack] -> [Protect Melee]
[Ally: Health < 25%] -> [Heal]

* What the system should be able to express
** Movement
+ Always move towards the enemy
+ Always move away from the enemy
+ Attempt to keep range at FIXED_RANGE
+ Attempt to keep at RANGE_OF_YOUR_WEAPON
+ Attempt to keep range at OPTIMUM_RANGE, where OPTIMUM_RANGE is a function of
  where your mech has superior firepower to their mech
+ Wait
** Weapons
+ Fire
+ Hold fire

Hmm. Currently the weapons possibilities are kind of slim because I don't have
Parts Targeting in yet, and there's no penalty (for example, BattleTech's Heat
system) for just firing all day, every day.

I haven't even implemented range brackets.

There is almost no reason to ever *not* fire. So I could just leave this right
now.
