Problem: If you have a Single Dominant Strategy, all optimization will converge
to that strategy. That's boring. So you don't want to have any Single Dominant
Strategy.

This is the balancing problem, and I'm sure you're familiar.

Here's my issue. My current game is too simple; the optimal strategy is *always*
either "Approach and attack" or "Run away and attack" based on some combination
of your mech's attributes and your opponent's mech's attributes at the beginning
of the match. If you have superior range DPS, run away, if you have superior
close range DPS, run towards.

There's the edge case where a bracket build will lose to a focused build but
that's still just "Get into optimal range and pound the foe until they die!"

So I need to add different strategies. I need to expand the option space.

* Locational Damage

If you can call your shots, you could have the strategy of "Shoot out the legs"
or "Shoot out the weapons" or something similar. This doesn't quite solve the
issue of build diversity, though.

* Rock-Paper-Scissors

Introducing hard-counters would definitely force different behaviours!

* Special-Case Equipment

Smoke grenades, for example, would allow melee mechs to move in towards the
enemy.
